//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Danasura_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class msBarang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public msBarang()
        {
            this.trPermintaanBarangs = new HashSet<trPermintaanBarang>();
        }
    
        public int id_barang { get; set; }
        public string nama { get; set; }
        public int id_kategori { get; set; }
        public string merk { get; set; }
        public Nullable<int> berat { get; set; }
        public int kondisi { get; set; }
        public string keterangan { get; set; }
        public int status { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_by { get; set; }
        public string foto_barang { get; set; }
        public Nullable<int> kuantitas { get; set; }
    
        public virtual msKategoriBarang msKategoriBarang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trPermintaanBarang> trPermintaanBarangs { get; set; }
    }
}
