//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Danasura_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class msSekolah
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public msSekolah()
        {
            this.msSiswas = new HashSet<msSiswa>();
        }
    
        public int id_sekolah { get; set; }


        [DisplayName("Nama Sekolah")]
        [Required(ErrorMessage = "Nama Sekolah harus diisi.")]
        public string nama_sekolah { get; set; }


        [DisplayName("Akreditasi")]
        public int akreditasi { get; set; }

        
        [DisplayName("Kontak")]
        [Required(ErrorMessage = "Kontak wajib diisi.")]
        [RegularExpression(@"^[a-zA-Z\s]+$", ErrorMessage = "Hanya menerima inputan huruf")]
        public string nama_cp { get; set; }


        [DisplayName("No. Kontak")]
        [Required(ErrorMessage = "No. Kontak wajib diisi.")]
        [RegularExpression(@"^[0-9]+$", ErrorMessage = "Hanya menerima inputan angka")]
        public string no_cp { get; set; }


        [DisplayName("Alamat Sekolah")]
        [Required(ErrorMessage = "Alamat Sekolah wajib diisi.")]
        public string alamat_sekolah { get; set; }


        [DisplayName("Provinsi")]
        [Required(ErrorMessage = "Provinsi wajib diisi.")]
        public string provinsi { get; set; }


        [DisplayName("Kota")]
        [Required(ErrorMessage = "Kota wajib diisi.")]
        public string kota { get; set; }


        [DisplayName("Kecamatan")]
        [Required(ErrorMessage = "Kecamatan wajib diisi.")]
        public string kecamatan { get; set; }


        [DisplayName("Jumlah Penerima KIP")]
        [RegularExpression(@"^[0-9]+$", ErrorMessage = "Hanya menerima inputan angka")]
        public Nullable<int> jml_penerimaKIP { get; set; }


        [DisplayName("Harga SPP")]
        [Required(ErrorMessage = "Harga SPP harus diisi.")]
        [RegularExpression(@"^[0-9]+$", ErrorMessage = "Hanya menerima inputan angka")]
        public decimal harga_spp { get; set; }


        [DisplayName("Harga Seragam")]
        [Required(ErrorMessage = "Harga Seragam harus diisi.")]
        [RegularExpression(@"^[0-9]+$", ErrorMessage = "Hanya menerima inputan angka")]
        public decimal harga_seragam { get; set; }


        [DisplayName("Deskripsi")]
        [Required(ErrorMessage = "Deskripsi harus diisi.")]
        public string deskripsi { get; set; }

        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_by { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<msSiswa> msSiswas { get; set; }
    }
}
