//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Danasura_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class msSiswa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public msSiswa()
        {
            this.trPencairanKuotas = new HashSet<trPencairanKuota>();
            this.trPengajuanSeragams = new HashSet<trPengajuanSeragam>();
            this.trPengajuanSPPs = new HashSet<trPengajuanSPP>();
            this.trPermintaanBarangs = new HashSet<trPermintaanBarang>();
        }
    
        public int id_siswa { get; set; }
        public string nisn { get; set; }
        public string nama { get; set; }
        public int jenis_kelamin { get; set; }
        public string tempat_lahir { get; set; }
        public Nullable<System.DateTime> tanggal_lahir { get; set; }
        public string alamat { get; set; }
        public string no_telp { get; set; }
        public string nomor_kip { get; set; }
        public int jenjang { get; set; }
        public int id_sekolah { get; set; }
        public Nullable<System.DateTime> semester_awal { get; set; }
        public Nullable<int> status { get; set; }
        public string nama_ayah { get; set; }
        public string pekerjaan_ayah { get; set; }
        public string nama_ibu { get; set; }
        public string pekerjaan_ibu { get; set; }
        public int sb_kuota { get; set; }
        public int sb_seragam { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_by { get; set; }
    
        public virtual dtNISNKJP dtNISNKJP { get; set; }
        public virtual msSekolah msSekolah { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trPencairanKuota> trPencairanKuotas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trPengajuanSeragam> trPengajuanSeragams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trPengajuanSPP> trPengajuanSPPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trPermintaanBarang> trPermintaanBarangs { get; set; }
    }
}
