//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Danasura_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class trPengajuanSeragam
    {
        public int id_trans { get; set; }

        [DisplayName("Tanggal Transaksi")]
        public System.DateTime tgl_trans { get; set; }

        [DisplayName("Pilih nama siswa")]
        public int id_siswa { get; set; }


        public Nullable<int> id_staff { get; set; }

        [DisplayName("Ukuran")]
        public int ukuran { get; set; }

        [DisplayName("Keterangan")]
        public string keterangan { get; set; }

        [DisplayName("Total Biaya")]
        [Required(ErrorMessage = "Total Biaya harus diisi.")]
        [RegularExpression(@"^[0-9]+$", ErrorMessage = "Hanya menerima inputan angka")]
        public decimal total_biaya { get; set; }


        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_by { get; set; }
    
        public virtual msSiswa msSiswa { get; set; }
        public virtual msStaff msStaff { get; set; }
    }
}
